def create_table(curr):
    create_table = ( """CREATE TABLE IF NOT EXISTS happiness  (

                    country_code VARCHAR(255) PRIMARY KEY,
                    Country TEXT NOT NULL,
                    sub_region TEXT NOT NULL,
                    intermediate_region TEXT NOT NULL,
                    dwelings_without_percentage REAL NOT NULL,
                    housing_expenditure REAL NOT NULL,
                    rooms_per_person REAL NOT NULL,
                    household_nadi REAL NOT NULL,
                    household_net_wealth REAL NOT NULL,
                    lmi_percentage REAL NOT NULL,
                    employment_rate REAL NOT NULL,
                    lt_unemplotyment_rate REAL NOT NULL,
                    personal_earnings REAL NOT NULL,
                    quality_support_network REAL NOT NULL,
                    educational_attachment_percentage REAL NOT NULL, 
                    student_scores REAL NOT NULL,
                    years_in_edu REAL NOT NULL,
                    mg_m3 REAL NOT NULL,
                    water_quality_percentage REAL NOT NULL,
                    stakeholder_engagement  REAL NOT NULL,
                    voter_turnout_pct  REAL NOT NULL,
                    life_expectancy  REAL NOT NULL,
                    self_support_health  REAL NOT NULL,
                    life_satisfaction_score REAL NOT NULL,
                    safe_at_night REAL NOT NULL,  
                    homicide_rate REAL NOT NULL,
                    employ_long_hours_pct REAL NOT NULL,
                    leisure_time REAL NOT NULL,
                    value  REAL NOT NULL
                    )
                      """ )
    curr.execute(create_table)

insert_command = ("""
                    INSERT INTO happiness (
                    country_code,
                    Country,
                    sub_region,
                    intermediate_region,
                    dwelings_without_percentage,
                    housing_expenditure,
                    rooms_per_person,
                    household_nadi,
                    household_net_wealth,
                    lmi_percentage,
                    employment_rate,
                    lt_unemplotyment_rate,
                    personal_earnings,
                    quality_support_network,
                    educational_attachment_percentage, 
                    student_scores,
                    years_in_edu,
                    mg_m3,
                    water_quality_percentage,
                    stakeholder_engagement,
                    voter_turnout_pct,
                    life_expectancy,
                    self_support_health,
                    life_satisfaction_score,
                    safe_at_night,  
                    homicide_rate,
                    employ_long_hours_pct,
                    leisure_time,
                    value

                     )
                     VALUES (
                       %s,
                    %s,
                    %s,
                    %s,
                    %s,
                    %s,
                    %s,
                    %s,
                    %s,
                    %s,
                    %s,
                    %s,
                    %s,
                    %s,
                    %s, 
                    %s,
                    %s,
                    %s,
                    %s,
                    %s,
                    %s,
                    %s,
                    %s,
                    %s,
                    %s,  
                    %s,
                    %s,
                    %s,
                    %s
                     );


                      """ )
def insert_into_table(insert_command, curr,
                  country_code,
                    Country,
                    sub_region,
                    intermediate_region,
                    dwelings_without_percentage,
                    housing_expenditure,
                    rooms_per_person,
                    household_nadi,
                    household_net_wealth,
                    lmi_percentage,
                    employment_rate,
                    lt_unemplotyment_rate,
                    personal_earnings,
                    quality_support_network,
                    educational_attachment_percentage, 
                    student_scores,
                    years_in_edu,
                    mg_m3,
                    water_quality_percentage,
                    stakeholder_engagement,
                    voter_turnout_pct,
                    life_expectancy,
                    self_support_health,
                    life_satisfaction_score,
                    safe_at_night,  
                    homicide_rate,
                    employ_long_hours_pct,
                    leisure_time,
                    value

      ) :
    row_to_insert = (country_code,
                    Country,
                    sub_region,
                    intermediate_region,
                    dwelings_without_percentage,
                    housing_expenditure,
                    rooms_per_person,
                    household_nadi,
                    household_net_wealth,
                    lmi_percentage,
                    employment_rate,
                    lt_unemplotyment_rate,
                    personal_earnings,
                    quality_support_network,
                    educational_attachment_percentage, 
                    student_scores,
                    years_in_edu,
                    mg_m3,
                    water_quality_percentage,
                    stakeholder_engagement,
                    voter_turnout_pct,
                    life_expectancy,
                    self_support_health,
                    life_satisfaction_score,
                    safe_at_night,  
                    homicide_rate,
                    employ_long_hours_pct,
                    leisure_time,
                    value)
    
    curr.execute(insert_command , row_to_insert)